// src/utils/iconResolver.js
import {
  Plane,
  PlaneTakeoff,
  ShieldCheck,
  Clock,
  Users,
  CheckCircle2,
  Star,
  Award,
  Headphones,
  Globe,
  Wallet,
  CreditCard,
  Luggage,
  MapPin,
  ThumbsUp,
  Heart,
  Lock,
  Wifi,
  Coffee,
  Umbrella,
  RefreshCcw,
  Phone,
  Mail,
  Sparkles,
} from "lucide-react";

// CMS-এ যেভাবেই সেভ থাকুক (FaPlane / fa-plane / MdFlight / IoAirplane / plane) — সবই normalize হয়ে একই key-তে মিলবে
const ICON_MAP = {
  plane: Plane,
  flight: Plane,
  airplane: Plane,
  planetakeoff: PlaneTakeoff,
  takeoff: PlaneTakeoff,
  departure: PlaneTakeoff,
  shield: ShieldCheck,
  shieldalt: ShieldCheck,
  security: ShieldCheck,
  safe: ShieldCheck,
  safety: ShieldCheck,
  clock: Clock,
  time: Clock,
  schedule: Clock,
  fast: Clock,
  ontime: Clock,
  users: Users,
  user: Users,
  team: Users,
  support: Users,
  check: CheckCircle2,
  checkcircle: CheckCircle2,
  verified: CheckCircle2,
  guarantee: CheckCircle2,
  star: Star,
  rating: Star,
  quality: Star,
  premium: Star,
  award: Award,
  badge: Award,
  trophy: Award,
  best: Award,
  headphones: Headphones,
  headset: Headphones,
  calling: Headphones,
  service: Headphones,
  customerservice: Headphones,
  globe: Globe,
  world: Globe,
  international: Globe,
  network: Globe,
  wallet: Wallet,
  price: Wallet,
  cost: Wallet,
  cheap: Wallet,
  afford: Wallet,
  affordable: Wallet,
  creditcard: CreditCard,
  payment: CreditCard,
  card: CreditCard,
  luggage: Luggage,
  baggage: Luggage,
  bag: Luggage,
  suitcase: Luggage,
  mappin: MapPin,
  location: MapPin,
  destination: MapPin,
  map: MapPin,
  thumbsup: ThumbsUp,
  like: ThumbsUp,
  satisfaction: ThumbsUp,
  heart: Heart,
  love: Heart,
  care: Heart,
  lock: Lock,
  secure: Lock,
  wifi: Wifi,
  internet: Wifi,
  connectivity: Wifi,
  coffee: Coffee,
  meal: Coffee,
  food: Coffee,
  umbrella: Umbrella,
  insurance: Umbrella,
  protection: Umbrella,
  refresh: RefreshCcw,
  refund: RefreshCcw,
  cancel: RefreshCcw,
  flexible: RefreshCcw,
  phone: Phone,
  call: Phone,
  contact: Phone,
  mail: Mail,
  email: Mail,
};

function normalize(name = "") {
  let s = name.toLowerCase().trim();
  s = s.replace(/^(fa-|fa|md-|md|io5-|io5|io-|io)/, ""); // FaPlane / fa-plane / MdFlight / IoAirplane প্রিফিক্স স্ট্রিপ
  s = s.replace(/[^a-z0-9]/g, ""); // dash/underscore/space বাদ
  return s;
}

/** সবসময় একটা valid React component রিটার্ন করে — না মিললে Sparkles (fallback), কখনো crash করবে না */
export function resolveIcon(name) {
  if (!name) return Sparkles;
  return ICON_MAP[normalize(name)] || Sparkles;
}
